### ISSUE TITLE
Always on top

### ISSUE THREAD

**Issue by NessunoIM** [DHIteration/DimScreen#4]
Is possible to make this program alway on top on windows 10?

When I open start menu, it go on top and dimscreen is "under"...

**Comment by DHIteration** [comment]
Ill take a look at it, when i wrote this i only had windows 7 at the time, Im now running Windows 10 so I load it up and see if i can fix or update anything I can.

**Comment by NessunoIM** [comment]
Thank you very much, you DimScreen is very useful. 👍

**Comment by NessunoIM** [comment]
Hi! News about Win 10 support?

**Comment by DHIteration** [comment]
Uploaded new code, hopefully fixes existing issues.

**Comment by NessunoIM** [comment]
Absolutely perfect!!! Thank you very much!!!
