### ISSUE TITLE
Taskbar remaines undimmed

### ISSUE THREAD

**Issue by AlexBerz** [DHIteration/DimScreen#5]
I tried to set it to hiding automatically, it didn't help.
![Screenshot_1](https://user-images.githubusercontent.com/45730581/74547391-b920c080-4f54-11ea-80c2-20362fdf1e95.png)
![Screenshot_2](https://user-images.githubusercontent.com/45730581/74547407-be7e0b00-4f54-11ea-9dec-0622c45045b1.png)

**Comment by DHIteration** [comment]
Uploaded new code, hopefully fixes existing issues.
